FROM python:3.11-slim

ENV BOOTSTRAP_SERVERS="kafka:19092"
ENV SCHEMA_REGISTRY_URL="http://kafka-schema-registry:8081"
ENV TOPIC_NAME="transactions"

WORKDIR /app
COPY . .

RUN pip install confluent-kafka urllib3 requests avro 
